### ISSUE TITLE
Rake 0.9 compatibility

### ISSUE THREAD

**Issue by bf4** [metricfu/metric_fu#17]
The Saikuro generator is not compatible with Rake 0.9. I got this while executing for a gem project; works with rake 0.8.7.

```
$ bundle exec rake metrics:all
rake aborted!
undefined method `sh' for #<MetricFu::Saikuro:0x1021d3938>
```

Rails 3.1 might be doing some magic/aliasing since I don't seem to have a problem there.
