### ISSUE TITLE
Instructions for Ruby 1.9+ compatibility

### ISSUE THREAD

**Issue by joonty** [metricfu/metric_fu#5]
Hi,

Thanks for picking up the baton on this project!

One thing that would be helpful is some information on how to get this working with Ruby 1.9+, as I just cannot see how to do it. I have to disable flog, flay, reek and rcov just to get it to run, due to parse errors.

(Incidentally, and possible a separate issue, both reek and rcov fail with the error 'undefined local variable or method 'class_name' for #MetricFu::LineNumbers:0x00000004dace98 @locations={}' - I'll open another issue if you aren't aware of this)

Do you also find this with ruby 1.9+ projects? Is there a good way to get the metrics working?

Thanks
